import re
from typing import Any

from helpers.constant import INDUSTRY_PATTERNS, SKILL_KEYWORDS

def _normalize_text(text: str) -> str:
    return " ".join(text.strip().split())


def _find_experience_years(text: str) -> int | None:
    lowered = text.lower()
    patterns = [
        r"(\d+(?:\.\d+)?)\s*(?:yr|yrs|years|year)\s*(?:of)?\s*experience",
        r"experience\s*(?:of)?\s*(\d+(?:\.\d+)?)\s*(?:yr|yrs|years|year)",
        r"(\d+(?:\.\d+)?)\s*(?:yr|yrs|years|year)\s*(?:working|developing|in)",
        r"(\d+(?:\.\d+)?)\s*(?:\+?)\s*years",
    ]

    for pattern in patterns:
        match = re.search(pattern, lowered)
        if match:
            try:
                return int(float(match.group(1)))
            except (ValueError, TypeError):
                return None

    return None


def _scrape_skills(text: str) -> list[str]:
    lowered = text.lower()
    skills = []

    # SKILL_KEYWORDS is a nested structure: category -> skill alias -> phrase list.
    # Flatten that nested structure and ask whether any alias is found in the resume body.
    for skill_group in SKILL_KEYWORDS.values():
        if not isinstance(skill_group, dict):
            continue

        for skill_name, patterns in skill_group.items():
            if any(keyword in lowered for keyword in patterns):
                skills.append(skill_name)

    # Fallback: pull common skill tokens from a "Skills" section
    skills_section_match = re.search(r"skills\s*[:\-](.*?)(?:experience|education|projects|summary|certifications|contact)", lowered, re.IGNORECASE | re.DOTALL)
    if skills_section_match:
        section = skills_section_match.group(1)
        tokens = [token.strip() for token in section.replace(",", " ").split()]
        for token in tokens:
            if len(token) > 2:
                skills.append(token)

    return sorted(set(skills))


def _infer_industry_type(text: str) -> str | None:
    lowered = text.lower()
    matched = []

    for industry, patterns in INDUSTRY_PATTERNS.items():
        if any(keyword in lowered for keyword in patterns):
            matched.append(industry)

    if matched:
        return matched[0]

    # If a resume mentions a domain-specific phrase not captured above, keep it as unknown-soft default.
    return "general"


def scrape_resume(resume_text: str | None, resume_url: str | None = None) -> dict[str, Any]:
    """
    Build a basic profile summary out of the raw resume content.

    It returns the fields expected by the API layer: skills, experience, industry_type, vector.
    """
    if not resume_text:
        if resume_url:
            import urllib.request

            with urllib.request.urlopen(resume_url, timeout=10) as response:
                payload = response.read().decode("utf-8", errors="ignore")
                resume_text = payload
        else:
            raise ValueError("A resume body or resume_url is required")

    if not resume_text or not str(resume_text).strip():
        raise ValueError("Resume text is empty")

    normalized = _normalize_text(resume_text)
    skills = _scrape_skills(normalized)
    experience = _find_experience_years(normalized)
    industry = _infer_industry_type(normalized)

    # Keep vector as an optional list payload. This can later be replaced with the
    # real embedding output generated by the LLM/embedding helper.
    vector = skills or []

    return {
        "skills": skills,
        "experience": experience,
        "industry_type": industry,
        "vector": vector,
    }
